# .github/workflows/e2e.yml

name: End-to-End Tests

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run End-to-End Tests
        # We simply run pytest. The test script itself will start the server,
        # run the tests against it, and then shut it down.
        run: pytest test_e2e.py -v