# .github/workflows/e2e.yml

name: Advanced End-to-End Tests

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Playwright E2E Tests
        # --- THIS IS THE FIX ---
        # We set the PYTHONPATH environment variable to '.' (the current directory).
        # This tells Python to add the project's root folder to its search path.
        # Now, when the test script says `from backend.database`, Python will
        # look in the root, find the `backend` folder, and the import will succeed.
        run: pytest -v tests/
        env:
          PYTHONPATH: .