# .github/workflows/e2e.yml

name: Advanced End-to-End Tests

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        # This crucial step downloads the headless browsers needed for Playwright to run in CI
        run: playwright install --with-deps

      - name: Run Playwright E2E Tests
        # Pytest will discover and run our test_e2e_flow.py script.
        # The test script itself handles starting and stopping the servers.
        run: pytest -v tests/